apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xul54ds28-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xul54ds28-go 
  name: xul54ds28-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xul54ds28-go 
